version: 2

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.6-jessie-node-browsers
    steps:
      - checkout
      - restore_cache:
          name: Restore npm package
          keys:
            - node-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          name: Save npm package
          key: node-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm run generate
      - run: sudo pip install awscli
      - run: aws s3 sync ./dist/ s3://houga.cc --exact-timestamps --delete --exclude "*.html" --cache-control max-age=31536000
      - run: aws s3 sync ./dist/ s3://houga.cc --exact-timestamps --delete --exclude "*" --include "*.html" --cache-control no-store
      - run: aws cloudfront create-invalidation --distribution-id $CF_DIST_ID --paths "/*"

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
